name: Deploy to Test

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to test.vitacapital.app
        uses: easingthemes/ssh-deploy@v6.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: eliasmaneiro
          SOURCE: ./
          TARGET: /var/www/test.vitacapital.app
          ARGS: -avz --delete
          EXCLUDE: "/.git/, /.github/"
          SCRIPT_BEFORE: |
            mkdir -p /var/www/test.vitacapital.app
            ls /var/www/test.vitacapital.app
